### ISSUE TITLE
官网找不到 kernel-2.6.32-279.23.1.el6.src.rpm 这个包

### ISSUE THREAD

**Issue by higkoo** [xiaomi-sa/dsnat#1]
官网6.2的版本最新是23.1，而6.3没有。是不是写错了？
另外：
1、啥时候支持6.4？
2、二进制包能放到Google上提供下载？
3、Keepalive和Ipvsadm能否也一起打成rpm包？

**Comment by xiaomi-org** [comment]
核对了一下代码版本，是我写错了，应该是kernel-2.6.32-279.el6.src.rpm
1 dsnat功能完善后，可能会考虑6.4的问题，任何时候都欢迎代码贡献者
2 二进制包在用的是公司定定制过的，回头会编译一个红帽默认配置的内核包。
3 工具包的编译版本已经放出

enjoy it！
